# Generated by Django 3.2.5 on 2022-11-18 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_apartments_raion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartments',
            name='raion',
        ),
    ]
