# Generated by Django 3.2.5 on 2022-11-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_apartment_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='square',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
