# Generated by Django 3.2.5 on 2022-11-18 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_apartment_e'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='e',
        ),
    ]
